"""remove_assistant_field_from_tasks

Revision ID: 6a15da3a4025
Revises: 7a967af6e4af
Create Date: 2026-02-27 01:37:09.894942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a15da3a4025'
down_revision = '7a967af6e4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('assistant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
