"""Remove color field from timelines table

Revision ID: 8fdb25f33c24
Revises: 32b225105901
Create Date: 2026-01-19 03:43:56.725084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdb25f33c24'
down_revision = '32b225105901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timelines', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
