"""remove progress field from timeline

Revision ID: a5efd8d22631
Revises: 8fdb25f33c24
Create Date: 2026-01-19 03:50:43.443777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5efd8d22631'
down_revision = '8fdb25f33c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timelines', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###
